<?php
/**
 * BasicMetric
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Velocloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * BasicMetric Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BasicMetric
{
    /**
     * Possible values of this enum
     */
    const PACKETS_RX = 'packetsRx';
    const PACKETS_TX = 'packetsTx';
    const TOTAL_PACKETS = 'totalPackets';
    const BYTES_RX = 'bytesRx';
    const BYTES_TX = 'bytesTx';
    const TOTAL_BYTES = 'totalBytes';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PACKETS_RX,
            self::PACKETS_TX,
            self::TOTAL_PACKETS,
            self::BYTES_RX,
            self::BYTES_TX,
            self::TOTAL_BYTES,
        ];
    }
}


