<?php
/**
 * LinkQualityObject
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Velocloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * LinkQualityObject Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class LinkQualityObject implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'link_quality_object';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'distribution' => 'object',
        'sample_count' => 'int',
        'sample_length' => 'int',
        'score' => 'object',
        'timeseries' => '\Swagger\Client\Model\LinkQualityObjectTimeseriesData[]',
        'total_score' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'distribution' => null,
        'sample_count' => null,
        'sample_length' => null,
        'score' => null,
        'timeseries' => null,
        'total_score' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'distribution' => 'distribution',
        'sample_count' => 'sampleCount',
        'sample_length' => 'sampleLength',
        'score' => 'score',
        'timeseries' => 'timeseries',
        'total_score' => 'totalScore'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'distribution' => 'setDistribution',
        'sample_count' => 'setSampleCount',
        'sample_length' => 'setSampleLength',
        'score' => 'setScore',
        'timeseries' => 'setTimeseries',
        'total_score' => 'setTotalScore'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'distribution' => 'getDistribution',
        'sample_count' => 'getSampleCount',
        'sample_length' => 'getSampleLength',
        'score' => 'getScore',
        'timeseries' => 'getTimeseries',
        'total_score' => 'getTotalScore'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['distribution'] = isset($data['distribution']) ? $data['distribution'] : null;
        $this->container['sample_count'] = isset($data['sample_count']) ? $data['sample_count'] : null;
        $this->container['sample_length'] = isset($data['sample_length']) ? $data['sample_length'] : null;
        $this->container['score'] = isset($data['score']) ? $data['score'] : null;
        $this->container['timeseries'] = isset($data['timeseries']) ? $data['timeseries'] : null;
        $this->container['total_score'] = isset($data['total_score']) ? $data['total_score'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['distribution'] === null) {
            $invalidProperties[] = "'distribution' can't be null";
        }
        if ($this->container['sample_count'] === null) {
            $invalidProperties[] = "'sample_count' can't be null";
        }
        if ($this->container['sample_length'] === null) {
            $invalidProperties[] = "'sample_length' can't be null";
        }
        if ($this->container['score'] === null) {
            $invalidProperties[] = "'score' can't be null";
        }
        if ($this->container['timeseries'] === null) {
            $invalidProperties[] = "'timeseries' can't be null";
        }
        if ($this->container['total_score'] === null) {
            $invalidProperties[] = "'total_score' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['distribution'] === null) {
            return false;
        }
        if ($this->container['sample_count'] === null) {
            return false;
        }
        if ($this->container['sample_length'] === null) {
            return false;
        }
        if ($this->container['score'] === null) {
            return false;
        }
        if ($this->container['timeseries'] === null) {
            return false;
        }
        if ($this->container['total_score'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets distribution
     *
     * @return object
     */
    public function getDistribution()
    {
        return $this->container['distribution'];
    }

    /**
     * Sets distribution
     *
     * @param object $distribution distribution
     *
     * @return $this
     */
    public function setDistribution($distribution)
    {
        $this->container['distribution'] = $distribution;

        return $this;
    }

    /**
     * Gets sample_count
     *
     * @return int
     */
    public function getSampleCount()
    {
        return $this->container['sample_count'];
    }

    /**
     * Sets sample_count
     *
     * @param int $sample_count sample_count
     *
     * @return $this
     */
    public function setSampleCount($sample_count)
    {
        $this->container['sample_count'] = $sample_count;

        return $this;
    }

    /**
     * Gets sample_length
     *
     * @return int
     */
    public function getSampleLength()
    {
        return $this->container['sample_length'];
    }

    /**
     * Sets sample_length
     *
     * @param int $sample_length sample_length
     *
     * @return $this
     */
    public function setSampleLength($sample_length)
    {
        $this->container['sample_length'] = $sample_length;

        return $this;
    }

    /**
     * Gets score
     *
     * @return object
     */
    public function getScore()
    {
        return $this->container['score'];
    }

    /**
     * Sets score
     *
     * @param object $score score
     *
     * @return $this
     */
    public function setScore($score)
    {
        $this->container['score'] = $score;

        return $this;
    }

    /**
     * Gets timeseries
     *
     * @return \Swagger\Client\Model\LinkQualityObjectTimeseriesData[]
     */
    public function getTimeseries()
    {
        return $this->container['timeseries'];
    }

    /**
     * Sets timeseries
     *
     * @param \Swagger\Client\Model\LinkQualityObjectTimeseriesData[] $timeseries timeseries
     *
     * @return $this
     */
    public function setTimeseries($timeseries)
    {
        $this->container['timeseries'] = $timeseries;

        return $this;
    }

    /**
     * Gets total_score
     *
     * @return float
     */
    public function getTotalScore()
    {
        return $this->container['total_score'];
    }

    /**
     * Sets total_score
     *
     * @param float $total_score total_score
     *
     * @return $this
     */
    public function setTotalScore($total_score)
    {
        $this->container['total_score'] = $total_score;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


