<?php
/**
 * DisasterRecoveryGetReplicationStatusResultTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Velocloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * DisasterRecoveryGetReplicationStatusResultTest Class Doc Comment
 *
 * @category    Class */
// * @description DisasterRecoveryGetReplicationStatusResult
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DisasterRecoveryGetReplicationStatusResultTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DisasterRecoveryGetReplicationStatusResult"
     */
    public function testDisasterRecoveryGetReplicationStatusResult()
    {
    }

    /**
     * Test attribute "active_address"
     */
    public function testPropertyActiveAddress()
    {
    }

    /**
     * Test attribute "active_replication_address"
     */
    public function testPropertyActiveReplicationAddress()
    {
    }

    /**
     * Test attribute "client_contact"
     */
    public function testPropertyClientContact()
    {
    }

    /**
     * Test attribute "client_count"
     */
    public function testPropertyClientCount()
    {
    }

    /**
     * Test attribute "dr_state"
     */
    public function testPropertyDrState()
    {
    }

    /**
     * Test attribute "dr_vco_user"
     */
    public function testPropertyDrVcoUser()
    {
    }

    /**
     * Test attribute "failure_description"
     */
    public function testPropertyFailureDescription()
    {
    }

    /**
     * Test attribute "last_dr_protected_time"
     */
    public function testPropertyLastDrProtectedTime()
    {
    }

    /**
     * Test attribute "role"
     */
    public function testPropertyRole()
    {
    }

    /**
     * Test attribute "role_timestamp"
     */
    public function testPropertyRoleTimestamp()
    {
    }

    /**
     * Test attribute "standby_list"
     */
    public function testPropertyStandbyList()
    {
    }

    /**
     * Test attribute "state_history"
     */
    public function testPropertyStateHistory()
    {
    }

    /**
     * Test attribute "state_timestamp"
     */
    public function testPropertyStateTimestamp()
    {
    }

    /**
     * Test attribute "vco_ip"
     */
    public function testPropertyVcoIp()
    {
    }

    /**
     * Test attribute "vco_replication_ip"
     */
    public function testPropertyVcoReplicationIp()
    {
    }

    /**
     * Test attribute "vco_uuid"
     */
    public function testPropertyVcoUuid()
    {
    }
}
