<?php
/**
 * DisasterRecoveryClientContactTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Velocloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.2.11
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * DisasterRecoveryClientContactTest Class Doc Comment
 *
 * @category    Class */
// * @description DisasterRecoveryClientContact
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DisasterRecoveryClientContactTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DisasterRecoveryClientContact"
     */
    public function testDisasterRecoveryClientContact()
    {
    }

    /**
     * Test attribute "active_address"
     */
    public function testPropertyActiveAddress()
    {
    }

    /**
     * Test attribute "active_last_response_time"
     */
    public function testPropertyActiveLastResponseTime()
    {
    }

    /**
     * Test attribute "client_logical_id"
     */
    public function testPropertyClientLogicalId()
    {
    }

    /**
     * Test attribute "client_type"
     */
    public function testPropertyClientType()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "modified"
     */
    public function testPropertyModified()
    {
    }

    /**
     * Test attribute "standby_address"
     */
    public function testPropertyStandbyAddress()
    {
    }

    /**
     * Test attribute "standby_last_response_time"
     */
    public function testPropertyStandbyLastResponseTime()
    {
    }
}
