<?php
/**
 * EdgeDeviceSettingsDataRoutedInterfacesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Velocloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.2.11
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * EdgeDeviceSettingsDataRoutedInterfacesTest Class Doc Comment
 *
 * @category    Class */
// * @description EdgeDeviceSettingsDataRoutedInterfaces
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EdgeDeviceSettingsDataRoutedInterfacesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EdgeDeviceSettingsDataRoutedInterfaces"
     */
    public function testEdgeDeviceSettingsDataRoutedInterfaces()
    {
    }

    /**
     * Test attribute "addressing"
     */
    public function testPropertyAddressing()
    {
    }

    /**
     * Test attribute "advertise"
     */
    public function testPropertyAdvertise()
    {
    }

    /**
     * Test attribute "disabled"
     */
    public function testPropertyDisabled()
    {
    }

    /**
     * Test attribute "dhcp_server"
     */
    public function testPropertyDhcpServer()
    {
    }

    /**
     * Test attribute "encrypt_overlay"
     */
    public function testPropertyEncryptOverlay()
    {
    }

    /**
     * Test attribute "l2"
     */
    public function testPropertyL2()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "nat_direct"
     */
    public function testPropertyNatDirect()
    {
    }

    /**
     * Test attribute "ospf"
     */
    public function testPropertyOspf()
    {
    }

    /**
     * Test attribute "override"
     */
    public function testPropertyOverride()
    {
    }

    /**
     * Test attribute "subinterfaces"
     */
    public function testPropertySubinterfaces()
    {
    }

    /**
     * Test attribute "vlan_id"
     */
    public function testPropertyVlanId()
    {
    }

    /**
     * Test attribute "wan_overlay"
     */
    public function testPropertyWanOverlay()
    {
    }

    /**
     * Test attribute "trusted"
     */
    public function testPropertyTrusted()
    {
    }

    /**
     * Test attribute "rpf"
     */
    public function testPropertyRpf()
    {
    }

    /**
     * Test attribute "underlay_accounting"
     */
    public function testPropertyUnderlayAccounting()
    {
    }
}
