<?php
/**
 * EdgeDeviceSettingsDataVrrpDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Velocloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * EdgeDeviceSettingsDataVrrpDataTest Class Doc Comment
 *
 * @category    Class */
// * @description EdgeDeviceSettingsDataVrrpData
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EdgeDeviceSettingsDataVrrpDataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EdgeDeviceSettingsDataVrrpData"
     */
    public function testEdgeDeviceSettingsDataVrrpData()
    {
    }

    /**
     * Test attribute "cidr_ip"
     */
    public function testPropertyCidrIp()
    {
    }

    /**
     * Test attribute "interface"
     */
    public function testPropertyInterface()
    {
    }

    /**
     * Test attribute "interval"
     */
    public function testPropertyInterval()
    {
    }

    /**
     * Test attribute "preempt"
     */
    public function testPropertyPreempt()
    {
    }

    /**
     * Test attribute "preempt_delay"
     */
    public function testPropertyPreemptDelay()
    {
    }

    /**
     * Test attribute "priority"
     */
    public function testPropertyPriority()
    {
    }

    /**
     * Test attribute "subinterface_id"
     */
    public function testPropertySubinterfaceId()
    {
    }

    /**
     * Test attribute "vlan_id"
     */
    public function testPropertyVlanId()
    {
    }

    /**
     * Test attribute "vrid"
     */
    public function testPropertyVrid()
    {
    }
}
