<?php
/**
 * EdgeDeviceSettingsDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Velocloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.2.11
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * EdgeDeviceSettingsDataTest Class Doc Comment
 *
 * @category    Class */
// * @description EdgeDeviceSettingsData
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EdgeDeviceSettingsDataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EdgeDeviceSettingsData"
     */
    public function testEdgeDeviceSettingsData()
    {
    }

    /**
     * Test attribute "bgp"
     */
    public function testPropertyBgp()
    {
    }

    /**
     * Test attribute "lan"
     */
    public function testPropertyLan()
    {
    }

    /**
     * Test attribute "routed_interfaces"
     */
    public function testPropertyRoutedInterfaces()
    {
    }

    /**
     * Test attribute "routes"
     */
    public function testPropertyRoutes()
    {
    }

    /**
     * Test attribute "ha"
     */
    public function testPropertyHa()
    {
    }

    /**
     * Test attribute "dns"
     */
    public function testPropertyDns()
    {
    }

    /**
     * Test attribute "netflow"
     */
    public function testPropertyNetflow()
    {
    }

    /**
     * Test attribute "vqm"
     */
    public function testPropertyVqm()
    {
    }

    /**
     * Test attribute "vrrp"
     */
    public function testPropertyVrrp()
    {
    }

    /**
     * Test attribute "snmp"
     */
    public function testPropertySnmp()
    {
    }

    /**
     * Test attribute "multi_source_qos"
     */
    public function testPropertyMultiSourceQos()
    {
    }

    /**
     * Test attribute "tacacs"
     */
    public function testPropertyTacacs()
    {
    }
}
