<?php
/**
 * EnterpriseProxyInsertEnterpriseProxyEnterpriseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Velocloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * EnterpriseProxyInsertEnterpriseProxyEnterpriseTest Class Doc Comment
 *
 * @category    Class */
// * @description EnterpriseProxyInsertEnterpriseProxyEnterprise
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EnterpriseProxyInsertEnterpriseProxyEnterpriseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EnterpriseProxyInsertEnterpriseProxyEnterprise"
     */
    public function testEnterpriseProxyInsertEnterpriseProxyEnterprise()
    {
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
    }

    /**
     * Test attribute "contact_email"
     */
    public function testPropertyContactEmail()
    {
    }

    /**
     * Test attribute "contact_mobile"
     */
    public function testPropertyContactMobile()
    {
    }

    /**
     * Test attribute "contact_name"
     */
    public function testPropertyContactName()
    {
    }

    /**
     * Test attribute "contact_phone"
     */
    public function testPropertyContactPhone()
    {
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
    }

    /**
     * Test attribute "lat"
     */
    public function testPropertyLat()
    {
    }

    /**
     * Test attribute "lon"
     */
    public function testPropertyLon()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "postal_code"
     */
    public function testPropertyPostalCode()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "street_address"
     */
    public function testPropertyStreetAddress()
    {
    }

    /**
     * Test attribute "street_address2"
     */
    public function testPropertyStreetAddress2()
    {
    }

    /**
     * Test attribute "gateway_pool_id"
     */
    public function testPropertyGatewayPoolId()
    {
    }

    /**
     * Test attribute "network_id"
     */
    public function testPropertyNetworkId()
    {
    }

    /**
     * Test attribute "return_data"
     */
    public function testPropertyReturnData()
    {
    }

    /**
     * Test attribute "user"
     */
    public function testPropertyUser()
    {
    }

    /**
     * Test attribute "configuration_id"
     */
    public function testPropertyConfigurationId()
    {
    }

    /**
     * Test attribute "enable_enterprise_delegation_to_operator"
     */
    public function testPropertyEnableEnterpriseDelegationToOperator()
    {
    }

    /**
     * Test attribute "enable_enterprise_delegation_to_proxy"
     */
    public function testPropertyEnableEnterpriseDelegationToProxy()
    {
    }

    /**
     * Test attribute "enable_enterprise_user_management_delegation_to_operator"
     */
    public function testPropertyEnableEnterpriseUserManagementDelegationToOperator()
    {
    }

    /**
     * Test attribute "enterprise_proxy_id"
     */
    public function testPropertyEnterpriseProxyId()
    {
    }
}
