<?php
/**
 * EnterpriseSetEnterpriseAllAlertRecipientsResultTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Velocloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * EnterpriseSetEnterpriseAllAlertRecipientsResultTest Class Doc Comment
 *
 * @category    Class */
// * @description EnterpriseSetEnterpriseAllAlertRecipientsResult
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EnterpriseSetEnterpriseAllAlertRecipientsResultTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EnterpriseSetEnterpriseAllAlertRecipientsResult"
     */
    public function testEnterpriseSetEnterpriseAllAlertRecipientsResult()
    {
    }

    /**
     * Test attribute "email_enabled"
     */
    public function testPropertyEmailEnabled()
    {
    }

    /**
     * Test attribute "email_list"
     */
    public function testPropertyEmailList()
    {
    }

    /**
     * Test attribute "enterprise_users"
     */
    public function testPropertyEnterpriseUsers()
    {
    }

    /**
     * Test attribute "mobile_enabled"
     */
    public function testPropertyMobileEnabled()
    {
    }

    /**
     * Test attribute "mobile_list"
     */
    public function testPropertyMobileList()
    {
    }

    /**
     * Test attribute "sms_enabled"
     */
    public function testPropertySmsEnabled()
    {
    }

    /**
     * Test attribute "sms_list"
     */
    public function testPropertySmsList()
    {
    }

    /**
     * Test attribute "snmp_enabled"
     */
    public function testPropertySnmpEnabled()
    {
    }

    /**
     * Test attribute "snmp_list"
     */
    public function testPropertySnmpList()
    {
    }
}
