<?php
/**
 * WANDataLinksTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Velocloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * WANDataLinksTest Class Doc Comment
 *
 * @category    Class */
// * @description WANDataLinks
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class WANDataLinksTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "WANDataLinks"
     */
    public function testWANDataLinks()
    {
    }

    /**
     * Test attribute "logical_id"
     */
    public function testPropertyLogicalId()
    {
    }

    /**
     * Test attribute "internal_id"
     */
    public function testPropertyInternalId()
    {
    }

    /**
     * Test attribute "discovery"
     */
    public function testPropertyDiscovery()
    {
    }

    /**
     * Test attribute "mode"
     */
    public function testPropertyMode()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "isp"
     */
    public function testPropertyIsp()
    {
    }

    /**
     * Test attribute "public_ip_address"
     */
    public function testPropertyPublicIpAddress()
    {
    }

    /**
     * Test attribute "source_ip_address"
     */
    public function testPropertySourceIpAddress()
    {
    }

    /**
     * Test attribute "next_hop_ip_address"
     */
    public function testPropertyNextHopIpAddress()
    {
    }

    /**
     * Test attribute "custom_vlan_id"
     */
    public function testPropertyCustomVlanId()
    {
    }

    /**
     * Test attribute "vlan_id"
     */
    public function testPropertyVlanId()
    {
    }

    /**
     * Test attribute "virtual_ip_address"
     */
    public function testPropertyVirtualIpAddress()
    {
    }

    /**
     * Test attribute "dynamic_bw_adjustment_enabled"
     */
    public function testPropertyDynamicBwAdjustmentEnabled()
    {
    }

    /**
     * Test attribute "bw_measurement"
     */
    public function testPropertyBwMeasurement()
    {
    }

    /**
     * Test attribute "upstream_mbps"
     */
    public function testPropertyUpstreamMbps()
    {
    }

    /**
     * Test attribute "downstream_mbps"
     */
    public function testPropertyDownstreamMbps()
    {
    }

    /**
     * Test attribute "backup_only"
     */
    public function testPropertyBackupOnly()
    {
    }

    /**
     * Test attribute "overhead_bytes"
     */
    public function testPropertyOverheadBytes()
    {
    }

    /**
     * Test attribute "udp_hole_punching"
     */
    public function testPropertyUdpHolePunching()
    {
    }

    /**
     * Test attribute "mtu"
     */
    public function testPropertyMtu()
    {
    }

    /**
     * Test attribute "mpls_network"
     */
    public function testPropertyMplsNetwork()
    {
    }

    /**
     * Test attribute "dscp_tag"
     */
    public function testPropertyDscpTag()
    {
    }

    /**
     * Test attribute "static_sla_enabled"
     */
    public function testPropertyStaticSlaEnabled()
    {
    }

    /**
     * Test attribute "classesof_service_enabled"
     */
    public function testPropertyClassesofServiceEnabled()
    {
    }

    /**
     * Test attribute "encrypt_overlay"
     */
    public function testPropertyEncryptOverlay()
    {
    }

    /**
     * Test attribute "static_sla"
     */
    public function testPropertyStaticSla()
    {
    }

    /**
     * Test attribute "classes_of_service"
     */
    public function testPropertyClassesOfService()
    {
    }

    /**
     * Test attribute "interfaces"
     */
    public function testPropertyInterfaces()
    {
    }

    /**
     * Test attribute "last_active"
     */
    public function testPropertyLastActive()
    {
    }
}
