<?php
/**
 * SystemPropertyApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Velocloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.2.11
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * SystemPropertyApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SystemPropertyApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for systemPropertyGetSystemProperties
     *
     * Get all system properties.
     *
     */
    public function testSystemPropertyGetSystemProperties()
    {
    }

    /**
     * Test case for systemPropertyGetSystemProperty
     *
     * Get system property.
     *
     */
    public function testSystemPropertyGetSystemProperty()
    {
    }

    /**
     * Test case for systemPropertyInsertOrUpdateSystemProperty
     *
     * Insert or update a system property.
     *
     */
    public function testSystemPropertyInsertOrUpdateSystemProperty()
    {
    }

    /**
     * Test case for systemPropertyInsertSystemProperty
     *
     * Insert a system property.
     *
     */
    public function testSystemPropertyInsertSystemProperty()
    {
    }

    /**
     * Test case for systemPropertyUpdateSystemProperty
     *
     * Update a system property.
     *
     */
    public function testSystemPropertyUpdateSystemProperty()
    {
    }
}
